---
layout: post
title: "c-CAD二次开发-模拟CAD移动图形,-通过圆现在注记,改变图形颜色"
date: 2024-10-06 10:48:23 +0800
description: "c# CAD二次开发 模拟CAD移动图形， 通过圆现在注记，改变图形颜色_c# 模拟cad 命令调用"
keywords: "c# 模拟cad 命令调用"
categories: ['未分类']
tags: ['开发语言', 'Linq', 'C']
artid: "130898179"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=130898179
  alt: "c-CAD二次开发-模拟CAD移动图形,-通过圆现在注记,改变图形颜色"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=130898179
featuredImagePreview: https://bing.ee123.net/img/rand?artid=130898179
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     c# CAD二次开发 模拟CAD移动图形， 通过圆现在注记，改变图形颜色
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="markdown_views prism-atom-one-dark" id="content_views">
    <svg style="display: none;" xmlns="http://www.w3.org/2000/svg">
     <path d="M5,0 0,2.5 5,5z" id="raphael-marker-block" stroke-linecap="round" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
     </path>
    </svg>
    <p>
     c# CAD二次开发 模拟CAD移动图形， 通过圆现在注记，改变图形颜色
     <br/>
     using Autodesk.AutoCAD.DatabaseServices;
     <br/>
     using Autodesk.AutoCAD.EditorInput;
     <br/>
     using Autodesk.AutoCAD.Geometry;
     <br/>
     using Autodesk.AutoCAD.Runtime;
     <br/>
     using System;
     <br/>
     using System.Collections.Generic;
     <br/>
     using System.Linq;
     <br/>
     using System.Text;
     <br/>
     using Application = Autodesk.AutoCAD.ApplicationServices.Application;
     <br/>
     using System.Windows.Forms;
    </p>
    <p>
     namespace _7_属性查找
     <br/>
     {
     <!-- -->
     <br/>
     public class Class1
     <br/>
     {
     <!-- -->
     <br/>
     ///
     <br/>
     /// 通过文本和扩展属性进行搜索
     <br/>
     ///
     <br/>
     [CommandMethod(“yesee”)]
     <br/>
     public void selectdemo()
     <br/>
     {
     <!-- -->
     <br/>
     Form1selecte form = new Form1selecte();
     <br/>
     form.Show();
     <br/>
     }
     <br/>
     ///
     <br/>
     /// 更新图形颜色
     <br/>
     ///
     <br/>
     ///
     <br/>
     private void changecolor(SelectionSet sset)
     <br/>
     {
     <!-- -->
     <br/>
     ObjectId[] ids = sset.GetObjectIds();
     <br/>
     Database db = HostApplicationServices.WorkingDatabase;
     <br/>
     using (Transaction trans = db.TransactionManager.StartTransaction())
     <br/>
     {
     <!-- -->
     <br/>
     for (int i = 0; i &lt; ids.Length; i++)
     <br/>
     {
     <!-- -->
     <br/>
     Entity ent = (Entity)ids[i].GetObject(OpenMode.ForWrite);
    </p>
    <pre><code>                ent.ColorIndex = 1;
                DBText textEntity = ent as DBText;
                string sTxt = textEntity.TextString;
            }
            trans.Commit();
        }
    }
    /// &lt;summary&gt;
    /// 通过选择圆来选择
    /// &lt;/summary&gt;
    [CommandMethod("yese1")]
    public void selectdemo1()
    {
        Database db = HostApplicationServices.WorkingDatabase;
        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //通过过滤器选择圆
        TypedValue[] values = new TypedValue[]
        {
            new TypedValue((int)DxfCode.Start,"circle")//选择图形为圆
        };
        SelectionFilter filter = new SelectionFilter(values);
        PromptSelectionResult psr = ed.GetSelection(filter);
        List&lt;ObjectId&gt; ids = new List&lt;ObjectId&gt;();
        if (psr.Status == PromptStatus.OK)
        {
            //遍历每个圆，将每个
            SelectionSet sset = psr.Value;
            List&lt;Point3d&gt; points = this.getpoint(sset);
            for (int i = 0; i &lt; points.Count; i++)
            {
                PromptSelectionResult ss1 = ed.SelectCrossingWindow(points.ElementAt(i), points.ElementAt(i));
                ids.AddRange(ss1.Value.GetObjectIds());
            }
        }
        this.changecolor1(ids);
    }
    /// &lt;summary&gt;
    /// 通过顶点选择集
    /// &lt;/summary&gt;
    /// &lt;param name="sset"&gt;&lt;/param&gt;
    /// &lt;returns&gt;&lt;/returns&gt;
    private List&lt;Point3d&gt; getpoint(SelectionSet sset)
    {
        List&lt;Point3d&gt; points = new List&lt;Point3d&gt;();
        ObjectId[] ids = sset.GetObjectIds();
        Database db = HostApplicationServices.WorkingDatabase;
        using (Transaction trans = db.TransactionManager.StartTransaction())
        {
            for (int i = 0; i &lt; ids.Length; i++)
            {
                Entity ent = (Entity)ids[i].GetObject(OpenMode.ForWrite);
                Point3d creter = ((Circle)ent).Center;
                double radius = ((Circle)ent).Radius;
                points.Add(new Point3d(creter.X + radius, creter.Y, creter.Z));
            }
            trans.Commit();
        }
        return points;
    }
    /// &lt;summary&gt;
    /// 更新图形颜色
    /// &lt;/summary&gt;
    /// &lt;param name="sset"&gt;&lt;/param&gt;
    private void changecolor1(List&lt;ObjectId&gt; ids)
    {
        Database db = HostApplicationServices.WorkingDatabase;
        using (Transaction trans = db.TransactionManager.StartTransaction())
        {
            for (int i = 0; i &lt; ids.Count; i++)
            {
                Entity ent = (Entity)ids[i].GetObject(OpenMode.ForWrite);
                ent.ColorIndex = 3;
            }
            trans.Commit();
        }
    }
    /// &lt;summary&gt;
    /// 动态交互,移动图形
    /// &lt;/summary&gt;
    [CommandMethod("yemove", CommandFlags.UsePickSet)]
    public void yemove()
    {
        Database db = HostApplicationServices.WorkingDatabase;
        Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
        //选择在命令前的图形
        PromptSelectionResult psr = ed.SelectImplied();
        //如果执行命令前没有选择对象，则执行选择
        if (psr.Status != PromptStatus.OK)
        {
            psr = ed.GetSelection();
        }
        if (psr.Status != PromptStatus.OK) return;
        //获取用户指定的基础点
        Point3d pointbase = new Point3d(0, 0, 0);
        PromptPointOptions ppo = new PromptPointOptions("\n 指定基点或[位移(D)]&lt;位移&gt;:");
        ppo.AllowNone = true;
        PromptPointResult ppr = ed.GetPoint(ppo);
        //判断用户指定基础点的输入
        if (ppr.Status == PromptStatus.Cancel) return;
        if (ppr.Status == PromptStatus.OK) pointbase = ppr.Value;

        //获取选择图形的图形对象
        List&lt;Entity&gt; entlist = new List&lt;Entity&gt;();
        //把选中的ID赋给ids
        ObjectId[] ids = psr.Value.GetObjectIds();
        entlist = this.getentity(ids);
        //改变源对象的颜色
        this.lowcolor(entlist, 211);
        //声明一个移动类
        MoveJig movejig = new MoveJig(entlist, pointbase);
        PromptResult pr = ed.Drag(movejig);
    }
    /// &lt;summary&gt;
    /// 将选择的对象转成Entity
    /// &lt;/summary&gt;
    /// &lt;param name="ids"&gt;图形列表&lt;/param&gt;
    /// &lt;returns&gt;&lt;/returns&gt;
    private List&lt;Entity&gt; getentity(ObjectId[] ids)
    {
        Database db = HostApplicationServices.WorkingDatabase;
        List&lt;Entity&gt; enlist = new List&lt;Entity&gt;();
        using (Transaction trans = db.TransactionManager.StartTransaction())
        {
            for (int i = 0; i &lt; ids.Length; i++)
            {
                Entity ent = (Entity)ids[i].GetObject(OpenMode.ForWrite);
                enlist.Add(ent);
            }
        }
        return enlist;
    }
    /// &lt;summary&gt;
    /// 改变图形对象的颜色
    /// &lt;/summary&gt;
    /// &lt;param name="enlist"&gt;图形对象&lt;/param&gt;
    /// &lt;param name="colorindex"&gt;颜色值&lt;/param&gt;
    private void lowcolor(List&lt;Entity&gt; enlist, int colorindex)
    {
        Database db = HostApplicationServices.WorkingDatabase;
        using (Transaction trans = db.TransactionManager.StartTransaction())
        {
            for (int i = 0; i &lt; enlist.Count; i++)
            {
                Entity ent = (Entity)enlist[i].ObjectId.GetObject(OpenMode.ForWrite);
                ent.ColorIndex = colorindex;
            }
            trans.Commit();
        }
    }

}
</code></pre>
<p>
}
</p>

   </div>
   <link href="../../assets/css/markdown_views-a5d25dd831.css" rel="stylesheet"/>
   <link href="../../assets/css/style-e504d6a974.css" rel="stylesheet"/>
  </div>
 </article>
 <p alt="68747470733a2f2f626c6f672e:6373646e2e6e65742f77656978696e5f34333933313937392f:61727469636c652f64657461696c732f313330383938313739" class_="artid" style="display:none">
 </p>
</div>
