---
layout: post
title: "Revit二次开发之移动元素比目鱼原创"
date: 2024-03-26 11:18:55 +0800
description: "本文介绍了如何使用 Revit API 中 ElementTransformUtils 类下的方法进"
keywords: "revitapi图元向上移动10厘米"
categories: ['基础', '几何数据', 'Revitapi']
tags: ['元素编辑', 'Revitapi']
artid: "78816928"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=78816928
    alt: "Revit二次开发之移动元素比目鱼原创"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=78816928
featuredImagePreview: https://bing.ee123.net/img/rand?artid=78816928
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     Revit二次开发之移动元素【比目鱼原创】
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="htmledit_views" id="content_views">
    API提供了移动元素的方法，可以把一个或者几个元素从一个地方移动到另一个地方，
    <br/>
    <p>
     Revit API提供ElementTransformUtils类下的
    </p>
    <p>
     MoveElement(Document document, ElementId elementToMove, XYZ translation)
    </p>
    <p>
     以及MoveElements(Document document, ICollection&lt;ElementId&gt; elementsToMove, XYZ translation)
    </p>
    <p>
     使用起来比较简单，
     <strong>
      <span style="color:#ff0000">
       但是有几个需要注意的地方
      </span>
     </strong>
     ：
    </p>
    <br/>
    ①
    <span style="white-space:pre">
    </span>
    移动方法不能远离标高向上或者向下移动一个基于标髙的元素。也就是说，当元素是基于标髙的，则不能改变Z轴坐标值，但可以移动元素到同一标高内的任意位置。例如， 如果在坐标点(0, 0, 0)新创建了一个柱子，然后移动它到新的坐标点（10, 20, 30)，这个柱 子将会移动到（10, 20, 0)，而不是(10, 20, 30)。
    <br/>
    <br/>
    ②
    <span style="white-space:pre">
    </span>
    当移动一个元素的时候，其他的元素也许会跟着移动。例如，如果—个墙上有窗户，这个墙移动了，窗户也会跟着移动。移动元素集的方法也会出现这种情况。例如，移动几根柱子的时候，所有与柱子连接着的梁也会跟着被移动或者会被改变长度。
    <br/>
    ③
    <span style="white-space:pre">
    </span>
    如果元素被钉住，即Pinned属性返回值是true，则表明这个元素不能被移动。如果仍然使用MoveEIement方法来移动这个元素，API就会抛出InvalidOperationException提示用户不能移动被钉住的元素。
    <br/>
    只外，还可以通过Location类来移动一个元素。Location类提供了移动和旋转的方法，而其子类提供了更多的Location信息和属性控制，如LocationPoint类和 locationCurve类。如果一个元素的Location可以转型为LocationCurve或者 LocationPoint，就可以直接移动这根线或者点到新的坐标点了。
    <br/>
    <pre><code class="language-csharp">Wall wall = element as Wall; 
if (null != wall) 
{ 
    LocationCurve wallLine = wall.Location as LocationCurve; 
    XYZ newPlace = new XYZ(10, 20, 0); 
    wallLine.Move(newPlace); 
} 
</code></pre>
    <p>
     上面的方法中，向量 (10, 20, 0)并不是目标坐标值， 而是一个偏移向量。
    </p>
    另外，LocationCurve 的 Curve 属性或者 LocationPoint 的Point属性也可以用来移动一个元素。
    <br/>
    Curve属性可以用来移动基于曲线的元素到精确的坐标点。 墙、梁、支撑等都通常用这个属性改变元素的长度。
    <br/>
    示例代码：
    <br/>
    <pre><code class="language-csharp">using(Transaction  tran  =  new  Transaction(projectDoc,  "Change  the  wall's  curve  with  a  new 
location line.")) 
{ 
  tran.Start(); 
                               
  LocationCurve wallLine = wall.Location as LocationCurve; 
  XYZ p1 = XYZ.Zero; 
  XYZ p2 = new XYZ(10, 20, 0); 
  Line newWallLine = Line.CreateBound(p1, p2); 
  // 把墙的位置线换成新的线 
  wallLine.Curve = newWallLine; 
                         
  tran.Commit(); 
} </code></pre>
    <br/>
    <p>
     利用LocationPoint的Point属性，可以设置元素的物理位置，如：
    </p>
    <p>
    </p>
    <pre><code class="language-csharp">FamilyInstance column = element as FamilyInstance; 
if (null != column) 
{ 
    LocationPoint columnPoint = column.Location as LocationPoint; 
    XYZ newLocation = new XYZ(10, 20, 0); 
    // 移动柱子到新的位置（10,20,0） 
    columnPoint.Point = newLocation; 
}</code></pre>
    <br/>
    <p style='margin-top:0px; margin-bottom:0px; padding-top:0px; padding-bottom:0px; color:rgb(85,85,85); font-family:"microsoft yahei"; font-size:15px'>
     <span style='font-family:"Microsoft YaHei","Helvetica Neue",SimSun; word-wrap:normal; word-break:normal; line-height:30px; font-size:20px'>
      =========【
     </span>
     <span style='font-family:"Microsoft YaHei","Helvetica Neue",SimSun; word-wrap:normal; word-break:normal; line-height:30px; font-size:20px'>
      更多高级应用请关注公众号
     </span>
     <span style='font-family:"Microsoft YaHei","Helvetica Neue",SimSun; word-wrap:normal; word-break:normal; line-height:30px; font-size:20px'>
      】========
     </span>
    </p>
    <p style='margin-top:0px; margin-bottom:0px; padding-top:0px; padding-bottom:0px; color:rgb(85,85,85); font-family:"microsoft yahei"; font-size:15px'>
    </p>
    <p style='margin-top:0px; margin-bottom:0px; padding-top:0px; padding-bottom:0px; color:rgb(85,85,85); font-family:"microsoft yahei"; font-size:15px'>
     <img alt="" src="https://img-blog.csdn.net/20171215213618491?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvYmJreHcwMDE=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center">
      <br/>
     </img>
    </p>
    <p style='margin-top:0px; margin-bottom:0px; padding-top:0px; padding-bottom:0px; color:rgb(85,85,85); font-family:"microsoft yahei"; font-size:15px'>
     <span style="font-size:18px">
      <span style='font-family:"Microsoft YaHei","Helvetica Neue",SimSun; word-wrap:normal; word-break:normal; line-height:30px; font-size:20px'>
       ===================================
      </span>
     </span>
    </p>
    <br/>
    <p>
    </p>
    <br/>
   </div>
  </div>
 </article>
 <p alt="6874747073:3a2f2f626c6f672e6373646e2e6e65742f62626b7877303031:2f61727469636c652f64657461696c732f3738383136393238" class_="artid" style="display:none">
 </p>
</div>


